"""create initial schema

Revision ID: e52c49458e50
Revises:
Create Date: 2026-08-26 17:23:31.156067

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e52c49458e50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champion',
    sa.Column('champion_id', sa.String(length=30), nullable=False),
    sa.Column('canonical_name', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('image_file', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('champion_id')
    )
    op.create_table('game_patch',
    sa.Column('patch_id', sa.String(length=20), nullable=False),
    sa.Column('patch_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('patch_id')
    )
    op.create_table('player',
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_name', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('team',
    sa.Column('team_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_name', sa.String(length=150), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('tournament',
    sa.Column('tournament_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('region', sa.String(length=30), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('tournament_id')
    )
    op.create_table('team_membership',
    sa.Column('membership_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('team_id', sa.String(length=64), nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('TOP', 'JUNGLE', 'MID', 'BOT', 'SUPPORT')", name='ck_team_membership_role'),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('membership_id')
    )
    op.create_index('ix_team_membership_player_validity', 'team_membership', ['player_id', 'valid_from', 'valid_to'], unique=False)
    op.create_index('ix_team_membership_team_validity', 'team_membership', ['team_id', 'valid_from', 'valid_to'], unique=False)
    op.create_table('tournament_stage',
    sa.Column('stage_id', sa.String(length=64), nullable=False),
    sa.Column('tournament_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.tournament_id'], ),
    sa.PrimaryKeyConstraint('stage_id')
    )
    op.create_table('series',
    sa.Column('series_id', sa.String(length=80), nullable=False),
    sa.Column('stage_id', sa.String(length=64), nullable=False),
    sa.Column('best_of', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('best_of IN (1, 3, 5)', name='ck_series_best_of'),
    sa.ForeignKeyConstraint(['stage_id'], ['tournament_stage.stage_id'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_table('game',
    sa.Column('game_id', sa.String(length=100), nullable=False),
    sa.Column('series_id', sa.String(length=80), nullable=False),
    sa.Column('patch_id', sa.String(length=20), nullable=False),
    sa.Column('game_number', sa.SmallInteger(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winner_team_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint('winner_team_id IS NULL OR ended_at IS NOT NULL', name='ck_game_winner_requires_end'),
    sa.ForeignKeyConstraint(['patch_id'], ['game_patch.patch_id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.series_id'], ),
    sa.ForeignKeyConstraint(['winner_team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index('ix_game_scheduled_at', 'game', ['scheduled_at'], unique=False)
    op.create_table('evaluation',
    sa.Column('evaluation_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('game_id', sa.String(length=100), nullable=False),
    sa.Column('evaluation_type', sa.String(length=4), nullable=False),
    sa.Column('blue_win_probability', sa.Double(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('history_cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_version', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pre_evaluation_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("(evaluation_type = 'PRE' AND pre_evaluation_id IS NULL) OR (evaluation_type = 'POST' AND pre_evaluation_id IS NOT NULL)", name='ck_evaluation_reference_shape'),
    sa.CheckConstraint("evaluation_type IN ('PRE', 'POST')", name='ck_evaluation_type'),
    sa.CheckConstraint('blue_win_probability >= 0 AND blue_win_probability <= 1', name='ck_evaluation_probability'),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['pre_evaluation_id'], ['evaluation.evaluation_id'], ),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_index('ix_evaluation_game_type', 'evaluation', ['game_id', 'evaluation_type'], unique=False)
    op.create_index('uq_evaluation_one_active_model', 'evaluation', ['game_id', 'evaluation_type', 'model_version'], unique=True, postgresql_where=sa.text('is_active IS TRUE'))
    op.create_table('game_team',
    sa.Column('game_team_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('game_id', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('confirmation_status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("side IN ('BLUE', 'RED')", name='ck_game_team_side'),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('game_team_id'),
    sa.UniqueConstraint('game_id', 'side', name='uq_game_team_game_side'),
    sa.UniqueConstraint('game_id', 'team_id', name='uq_game_team_game_team')
    )
    op.create_index('ix_game_team_team_id', 'game_team', ['team_id'], unique=False)
    op.create_table('evaluation_warning',
    sa.Column('warning_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('evaluation_id', sa.BigInteger(), nullable=False),
    sa.Column('warning_group', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation.evaluation_id'], ),
    sa.PrimaryKeyConstraint('warning_id')
    )
    op.create_table('game_player',
    sa.Column('game_player_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('game_team_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('champion_id', sa.String(length=30), nullable=True),
    sa.Column('confirmation_status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("role IN ('TOP', 'JUNGLE', 'MID', 'BOT', 'SUPPORT')", name='ck_game_player_role'),
    sa.ForeignKeyConstraint(['champion_id'], ['champion.champion_id'], ),
    sa.ForeignKeyConstraint(['game_team_id'], ['game_team.game_team_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('game_player_id'),
    sa.UniqueConstraint('game_team_id', 'role', name='uq_game_player_game_team_role')
    )
    op.create_index('ix_game_player_champion_id', 'game_player', ['champion_id'], unique=False)
    op.create_index('ix_game_player_player_id', 'game_player', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_player_player_id', table_name='game_player')
    op.drop_index('ix_game_player_champion_id', table_name='game_player')
    op.drop_table('game_player')
    op.drop_table('evaluation_warning')
    op.drop_index('ix_game_team_team_id', table_name='game_team')
    op.drop_table('game_team')
    op.drop_index('uq_evaluation_one_active_model', table_name='evaluation', postgresql_where=sa.text('is_active IS TRUE'))
    op.drop_index('ix_evaluation_game_type', table_name='evaluation')
    op.drop_table('evaluation')
    op.drop_index('ix_game_scheduled_at', table_name='game')
    op.drop_table('game')
    op.drop_table('series')
    op.drop_table('tournament_stage')
    op.drop_index('ix_team_membership_team_validity', table_name='team_membership')
    op.drop_index('ix_team_membership_player_validity', table_name='team_membership')
    op.drop_table('team_membership')
    op.drop_table('tournament')
    op.drop_table('team')
    op.drop_table('player')
    op.drop_table('game_patch')
    op.drop_table('champion')
    # ### end Alembic commands ###
