"""Transform Oracle core data into PostgreSQL-shaped dry-run records.

The module is deliberately pure: it receives normalized source data, resolved
identities, and an optional read-only target snapshot.  It never reads files or
opens a database connection.
"""

from __future__ import annotations

import hashlib
import json
import re
import unicodedata
from dataclasses import dataclass, field
from typing import Final
from urllib.parse import parse_qs, urlsplit

import pandas as pd

from match_insight.data_processing.oracle_etl import OracleCoreData
from match_insight.data_processing.oracle_identity import (
    CHAMPION_MAPPED,
    TARGET_CONFLICT,
    TARGET_EXISTING,
    TARGET_NEW_REQUIRED,
    UNRESOLVED,
    OracleIdentityResult,
)
from match_insight.data_processing.reference_common import canonical_key

SERIES_READY: Final[str] = "READY"
SERIES_BLOCKED: Final[str] = "BLOCKED"

GAME_TRANSFORM_READY: Final[str] = "READY"
GAME_TRANSFORM_PARTIAL: Final[str] = "PARTIAL"
GAME_TRANSFORM_BLOCKED: Final[str] = "BLOCKED"

SOURCE_REPORTED: Final[str] = "SOURCE_REPORTED"
SOURCE_CHAMPION_UNMAPPED: Final[str] = "CHAMPION_UNMAPPED"

TARGET_TABLE_ORDER: Final[tuple[str, ...]] = (
    "game_patch",
    "tournament",
    "tournament_stage",
    "series",
    "team",
    "player",
    "game",
    "game_team",
    "game_player",
)

# Apply uses COALESCE for these fields.  Dry-run comparison must mirror that
# existing contract so a NULL candidate does not forecast a write that apply
# would preserve.
PRESERVE_ON_NULL_COLUMNS: Final[dict[str, frozenset[str]]] = {
    "team": frozenset({"logo_file"}),
    "player": frozenset({"photo_file"}),
    "game": frozenset({"started_at", "ended_at"}),
}

SIDE_MAP: Final[dict[str, str]] = {
    "blue": "BLUE",
    "red": "RED",
}

ROLE_MAP: Final[dict[str, str]] = {
    "top": "TOP",
    "jng": "JUNGLE",
    "mid": "MID",
    "bot": "BOT",
    "sup": "SUPPORT",
}

GAME_PATCH_COLUMNS: Final[tuple[str, ...]] = (
    "patch_id",
    "patch_name",
)
TOURNAMENT_COLUMNS: Final[tuple[str, ...]] = (
    "tournament_id",
    "name",
    "region",
    "season",
)
TOURNAMENT_STAGE_COLUMNS: Final[tuple[str, ...]] = (
    "stage_id",
    "tournament_id",
    "name",
)
SERIES_COLUMNS: Final[tuple[str, ...]] = (
    "series_id",
    "stage_id",
    "best_of",
)
TEAM_COLUMNS: Final[tuple[str, ...]] = (
    "team_id",
    "oracle_team_id",
    "canonical_name",
    "display_name",
    "logo_file",
)
PLAYER_COLUMNS: Final[tuple[str, ...]] = (
    "player_id",
    "oracle_player_id",
    "canonical_name",
    "display_name",
    "photo_file",
)
GAME_COLUMNS: Final[tuple[str, ...]] = (
    "game_id",
    "series_id",
    "stage_id",
    "patch_id",
    "game_number",
    "scheduled_at",
    "started_at",
    "ended_at",
    "winner_team_id",
)
GAME_TEAM_COLUMNS: Final[tuple[str, ...]] = (
    "game_id",
    "team_id",
    "side",
    "confirmation_status",
)

# ``game_team_id`` is generated by PostgreSQL.  The dry-run therefore keeps a
# logical (game_id, side) link which Step 6F can resolve inside its transaction.
GAME_PLAYER_COLUMNS: Final[tuple[str, ...]] = (
    "game_id",
    "side",
    "player_id",
    "role",
    "champion_id",
    "confirmation_status",
)

ISSUE_COLUMNS: Final[tuple[str, ...]] = (
    "entity",
    "source_key",
    "reason",
    "detail",
)
ACTION_COLUMNS: Final[tuple[str, ...]] = (
    "table",
    "source_key",
    "action",
)
UNMAPPED_CHAMPION_COLUMNS: Final[tuple[str, ...]] = (
    "gameid",
    "side",
    "position",
    "champion",
    "reason",
)
REJECTED_GAME_COLUMNS: Final[tuple[str, ...]] = (
    "gameid",
    "primary_reason",
    "secondary_reasons",
    "league",
    "source_year",
    "calendar_date",
    "patch",
    "split",
    "datacompleteness",
    "blue_team",
    "red_team",
    "detail",
)

_SERIES_RECORD_COLUMNS: Final[tuple[str, ...]] = (
    "series_id",
    "source_series_key",
    "league",
    "year",
    "split",
    "playoffs",
    "best_of",
)
_SERIES_ASSIGNMENT_COLUMNS: Final[tuple[str, ...]] = (
    "gameid",
    "series_id",
    "series_status",
    "series_reason",
)
_SERIES_DIAGNOSTIC_COLUMNS: Final[tuple[str, ...]] = (
    "source_key",
    "status",
    "reason",
    "detail",
)

_GAME_SERIES_PATTERN: Final[re.Pattern[str]] = re.compile(
    r"^(?P<series>.+?)[_-]game[_-](?P<number>\d+)$",
    flags=re.IGNORECASE,
)
_BEST_OF_TOKEN_PATTERN: Final[re.Pattern[str]] = re.compile(
    r"(?:^|[^a-z0-9])bo(?P<best_of>[135])(?:[^a-z0-9]|$)",
    flags=re.IGNORECASE,
)
_URL_SERIES_PARAMETERS: Final[tuple[str, ...]] = (
    "seriesid",
    "series_id",
    "matchid",
    "match_id",
    "bmid",
)
_URL_BEST_OF_PARAMETERS: Final[tuple[str, ...]] = (
    "bestof",
    "best_of",
    "bo",
)
_EXPECTED_ROLES: Final[frozenset[str]] = frozenset(ROLE_MAP.values())


def _empty_frame(columns: tuple[str, ...]) -> pd.DataFrame:
    return pd.DataFrame(columns=list(columns))


@dataclass(frozen=True)
class OracleSeriesAnalysis:
    """Evidence-based series result at series and game grain."""

    status: str
    series_records: pd.DataFrame
    diagnostics: pd.DataFrame
    game_assignments: pd.DataFrame


@dataclass(frozen=True)
class OracleTargetSnapshot:
    """Read-only target rows supplied by a caller for dry-run comparison."""

    game_patches: pd.DataFrame = field(
        default_factory=lambda: _empty_frame(GAME_PATCH_COLUMNS)
    )
    tournaments: pd.DataFrame = field(
        default_factory=lambda: _empty_frame(TOURNAMENT_COLUMNS)
    )
    tournament_stages: pd.DataFrame = field(
        default_factory=lambda: _empty_frame(TOURNAMENT_STAGE_COLUMNS)
    )
    series: pd.DataFrame = field(
        default_factory=lambda: _empty_frame(SERIES_COLUMNS)
    )
    teams: pd.DataFrame = field(
        default_factory=lambda: _empty_frame(TEAM_COLUMNS)
    )
    players: pd.DataFrame = field(
        default_factory=lambda: _empty_frame(PLAYER_COLUMNS)
    )
    games: pd.DataFrame = field(
        default_factory=lambda: _empty_frame(GAME_COLUMNS)
    )
    game_teams: pd.DataFrame = field(
        default_factory=lambda: _empty_frame(GAME_TEAM_COLUMNS)
    )
    game_players: pd.DataFrame = field(
        default_factory=lambda: _empty_frame(GAME_PLAYER_COLUMNS)
    )


@dataclass(frozen=True)
class OracleTargetRecords:
    """Nine target-shaped DataFrames in foreign-key order."""

    game_patches: pd.DataFrame
    tournaments: pd.DataFrame
    tournament_stages: pd.DataFrame
    series: pd.DataFrame
    teams: pd.DataFrame
    players: pd.DataFrame
    games: pd.DataFrame
    game_teams: pd.DataFrame
    game_players: pd.DataFrame


@dataclass(frozen=True)
class OracleDryRunResult:
    """Transform output plus every non-transformed reason."""

    records: OracleTargetRecords
    unresolved_records: pd.DataFrame
    rejected_records: pd.DataFrame
    skipped_records: pd.DataFrame
    unmapped_champions: pd.DataFrame
    series_analysis: OracleSeriesAnalysis
    actions: pd.DataFrame
    source_counts: dict[str, int]
    rejected_games: pd.DataFrame = field(
        default_factory=lambda: _empty_frame(REJECTED_GAME_COLUMNS)
    )


def _is_missing(value: object) -> bool:
    if value is None:
        return True
    return bool(pd.isna(value))


def _text_or_none(value: object) -> str | None:
    if _is_missing(value):
        return None
    text = unicodedata.normalize("NFKC", str(value))
    cleaned = " ".join(text.split())
    return cleaned or None


def _issue(
    entity: str,
    source_key: object,
    reason: str,
    detail: str,
) -> dict[str, str]:
    return {
        "entity": entity,
        "source_key": str(source_key),
        "reason": reason,
        "detail": detail,
    }


def _records_frame(
    records: list[dict[str, object]],
    columns: tuple[str, ...],
) -> pd.DataFrame:
    if not records:
        return _empty_frame(columns)
    return pd.DataFrame.from_records(records).loc[:, list(columns)]


def _stable_id(prefix: str, *parts: object, maximum: int = 64) -> str:
    payload = "\x1f".join(
        "<NULL>" if _is_missing(part) else str(part) for part in parts
    )
    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    return f"{prefix}{digest[: maximum - len(prefix)]}"


def _single_group_value(
    group: pd.DataFrame,
    column: str,
    *,
    required: bool,
) -> tuple[object, str | None]:
    values = group[column]
    missing_mask = values.map(_is_missing)
    non_missing = values.loc[~missing_mask].drop_duplicates()

    if len(non_missing) > 1:
        if not required:
            return pd.NA, None
        return None, f"CONFLICTING_{column.upper()}"
    if bool(missing_mask.any()) and len(non_missing) == 1:
        if not required:
            return pd.NA, None
        return None, f"MIXED_MISSING_{column.upper()}"
    if non_missing.empty:
        if required:
            return None, f"MISSING_{column.upper()}"
        return pd.NA, None
    return non_missing.iloc[0], None


def _url_evidence_by_game(
    core_data: OracleCoreData,
) -> tuple[dict[str, str | None], dict[str, str]]:
    """Keep URL evidence only when every source row agrees.

    URL is optional target metadata.  Mixed missing or conflicting values must
    not reject an otherwise usable game, but neither condition may be resolved
    by selecting one URL for series evidence.
    """

    urls: dict[str, str | None] = {}
    anomalies: dict[str, str] = {}
    source = core_data.dataframe
    valid_gameids = source.loc[~source["gameid"].map(_is_missing)]
    for gameid, group in valid_gameids.groupby(
        "gameid",
        sort=False,
        dropna=False,
    ):
        source_key = str(gameid)
        cleaned = [_text_or_none(value) for value in group["url"].tolist()]
        non_missing = {value for value in cleaned if value is not None}
        has_missing = any(value is None for value in cleaned)
        if len(non_missing) > 1:
            urls[source_key] = None
            anomalies[source_key] = "URL_VALUES_CONFLICT"
        elif len(non_missing) == 1 and has_missing:
            urls[source_key] = None
            anomalies[source_key] = "URL_MIXED_MISSING"
        elif non_missing:
            urls[source_key] = next(iter(non_missing))
        else:
            urls[source_key] = None
    return urls, anomalies


def _collapse_game_metadata(
    core_data: OracleCoreData,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    source = core_data.dataframe
    required_columns = {
        "gameid",
        "url",
        "league",
        "year",
        "split",
        "playoffs",
        "date",
        "game",
        "patch",
    }
    missing_columns = sorted(required_columns - set(source.columns))
    if missing_columns:
        raise ValueError(
            "Oracle core data is missing transform columns: "
            + ", ".join(missing_columns)
        )

    records: list[dict[str, object]] = []
    rejected: list[dict[str, str]] = []
    missing_gameid = source["gameid"].map(_is_missing)
    if bool(missing_gameid.any()):
        sample_indices = source.index[missing_gameid].tolist()[:20]
        raise ValueError(
            "Oracle transform cannot establish game grain because gameid is "
            f"missing for {int(missing_gameid.sum())} source row(s); "
            f"sample_indices={sample_indices}. No source or target ID was "
            "fabricated."
        )

    grouped = source.loc[~missing_gameid].groupby(
        "gameid",
        sort=False,
        dropna=False,
    )
    fields = (
        ("url", False),
        ("league", True),
        ("year", True),
        ("split", True),
        ("playoffs", True),
        ("date", True),
        ("game", True),
        ("patch", True),
    )

    for gameid, group in grouped:
        record: dict[str, object] = {"gameid": str(gameid)}
        reasons: list[str] = []
        for column, required in fields:
            value, reason = _single_group_value(
                group,
                column,
                required=required,
            )
            record[column] = value
            if reason is not None:
                reasons.append(reason)

        if not reasons:
            game_number = int(record["game"])
            season = int(record["year"])
            patch = str(record["patch"])
            if not 1 <= game_number <= 32767:
                reasons.append("INVALID_GAME_NUMBER")
            if not -32768 <= season <= 32767:
                reasons.append("INVALID_SOURCE_YEAR")
            if len(patch) > 20:
                reasons.append("PATCH_TOO_LONG")
            if len(str(gameid)) > 100:
                reasons.append("GAME_ID_TOO_LONG")

        if reasons:
            rejected.append(
                _issue(
                    "game",
                    gameid,
                    "GAME_METADATA_INVALID",
                    ",".join(sorted(reasons)),
                )
            )
            continue
        records.append(record)

    columns = (
        "gameid",
        "url",
        "league",
        "year",
        "split",
        "playoffs",
        "date",
        "game",
        "patch",
    )
    return (
        _records_frame(records, columns),
        _records_frame(rejected, ISSUE_COLUMNS),
    )


def _series_key_from_gameid(
    gameid: str,
    game_number: int,
) -> tuple[str | None, str | None]:
    match = _GAME_SERIES_PATTERN.fullmatch(gameid)
    if match is None:
        return None, None
    encoded_number = int(match.group("number"))
    if encoded_number != game_number:
        return None, "GAMEID_GAME_NUMBER_CONFLICT"
    key = _text_or_none(match.group("series"))
    if key is None:
        return None, "EMPTY_GAMEID_SERIES_KEY"
    return key, None


def _series_key_from_url(url: object) -> tuple[str | None, str | None]:
    text = _text_or_none(url)
    if text is None:
        return None, None
    try:
        parsed = urlsplit(text)
    except ValueError:
        return None, "INVALID_URL_EVIDENCE"
    parameters = parse_qs(parsed.query, keep_blank_values=False)
    candidates: list[str] = []
    for name in _URL_SERIES_PARAMETERS:
        values = sorted(set(parameters.get(name, ())))
        candidates.extend(
            f"{parsed.netloc.casefold()}?{name}={value}"
            for value in values
            if value
        )
    candidates = sorted(set(candidates))
    if len(candidates) > 1:
        return None, "AMBIGUOUS_URL_SERIES_KEY"
    if not candidates:
        return None, None
    return candidates[0], None


def _explicit_best_of(*values: object) -> tuple[int | None, str | None]:
    candidates: set[int] = set()
    for value in values:
        text = _text_or_none(value)
        if text is None:
            continue
        try:
            parsed = urlsplit(text)
        except ValueError:
            # URL evidence is diagnosed by ``_series_key_from_url``.  It must
            # not crash or contribute a best-of token after parsing failed.
            continue
        candidates.update(
            int(match.group("best_of"))
            for match in _BEST_OF_TOKEN_PATTERN.finditer(text)
        )
        parameters = parse_qs(parsed.query, keep_blank_values=False)
        for name in _URL_BEST_OF_PARAMETERS:
            for parameter_value in parameters.get(name, ()):
                normalized = parameter_value.strip().casefold()
                if normalized.startswith("bo"):
                    normalized = normalized[2:]
                if normalized in {"1", "3", "5"}:
                    candidates.add(int(normalized))

    if len(candidates) > 1:
        return None, "EXPLICIT_BEST_OF_CONFLICT"
    if not candidates:
        return None, "EXPLICIT_BEST_OF_MISSING"
    return next(iter(candidates)), None


def _team_pair_by_game(
    identity_result: OracleIdentityResult,
) -> dict[str, tuple[str, str]]:
    teams = identity_result.team_participations
    required = {"gameid", "resolved_oracle_team_id"}
    if not required <= set(teams.columns):
        raise ValueError("Oracle team resolutions are missing series columns.")

    pairs: dict[str, tuple[str, str]] = {}
    for gameid, group in teams.groupby("gameid", sort=False, dropna=False):
        values = sorted(
            {
                str(value)
                for value in group["resolved_oracle_team_id"].tolist()
                if not _is_missing(value)
            }
        )
        if len(values) == 2:
            pairs[str(gameid)] = (values[0], values[1])
    return pairs


def analyze_series_evidence(
    core_data: OracleCoreData,
    identity_result: OracleIdentityResult,
) -> OracleSeriesAnalysis:
    """Resolve only source-explicit series keys and best-of tokens.

    Team pair, date, and game number validate a source key.  They are never
    used to manufacture a key or infer BO1/BO3/BO5.
    """

    games, metadata_rejected = _collapse_game_metadata(core_data)
    pairs = _team_pair_by_game(identity_result)
    urls_by_game, url_anomalies = _url_evidence_by_game(core_data)
    candidates: list[dict[str, object]] = []
    assignments: list[dict[str, object]] = []
    diagnostics: list[dict[str, str]] = []
    url_gameid_conflicts: set[str] = set()

    valid_gameids = {str(value) for value in games["gameid"].tolist()}
    url_to_gameids: dict[str, set[str]] = {}
    for gameid, source_url in urls_by_game.items():
        if gameid not in valid_gameids or source_url is None:
            continue
        url_to_gameids.setdefault(source_url, set()).add(gameid)
    for related_gameids in url_to_gameids.values():
        if len(related_gameids) > 1:
            url_gameid_conflicts.update(related_gameids)

    for row in games.itertuples(index=False):
        gameid = str(row.gameid)
        game_number = int(row.game)
        source_url = urls_by_game.get(gameid)
        gameid_key, gameid_reason = _series_key_from_gameid(
            gameid,
            game_number,
        )
        url_key, url_reason = _series_key_from_url(source_url)
        reasons = [
            reason
            for reason in (gameid_reason, url_reason)
            if reason is not None
        ]
        url_anomaly = url_anomalies.get(gameid)
        if url_anomaly is not None:
            reasons.append(url_anomaly)
        source_key = gameid_key or url_key
        if gameid_key is not None and url_key is not None:
            source_key = gameid_key

        best_of, best_of_reason = _explicit_best_of(gameid, source_url)
        if best_of_reason is not None:
            reasons.append(best_of_reason)
        if source_key is None:
            reasons.append("SOURCE_SERIES_KEY_MISSING")
        if gameid in url_gameid_conflicts:
            reasons.append("URL_TO_GAMEID_CONFLICT")
        if gameid not in pairs:
            reasons.append("TEAM_PAIR_UNRESOLVED")

        if reasons:
            reason = ",".join(sorted(set(reasons)))
            assignments.append(
                {
                    "gameid": gameid,
                    "series_id": pd.NA,
                    "series_status": SERIES_BLOCKED,
                    "series_reason": reason,
                }
            )
            diagnostics.append(
                {
                    "source_key": gameid,
                    "status": SERIES_BLOCKED,
                    "reason": reason,
                    "detail": "No series record was created for this game.",
                }
            )
            continue

        candidates.append(
            {
                "gameid": gameid,
                "source_series_key": str(source_key),
                "url_series_key": url_key,
                "source_url": source_url,
                "league": row.league,
                "year": row.year,
                "split": row.split,
                "playoffs": row.playoffs,
                "date": row.date,
                "game_number": game_number,
                "team_pair": pairs[gameid],
                "best_of": int(best_of),
            }
        )

    candidate_frame = pd.DataFrame.from_records(candidates)
    series_records: list[dict[str, object]] = []
    conflicting_source_keys: set[str] = set()
    if not candidate_frame.empty:
        # A URL-derived identifier may describe several games in one series;
        # the exact URL -> gameid dependency was validated above.  Neither form
        # may point at several source series.  URL/date/team pair never
        # manufacture a series key.
        for relation_column in ("url_series_key", "source_url"):
            relation_rows = candidate_frame.loc[
                ~candidate_frame[relation_column].map(_is_missing)
            ]
            for _, relation_group in relation_rows.groupby(
                relation_column,
                sort=False,
                dropna=False,
            ):
                related_keys = {
                    str(value)
                    for value in relation_group["source_series_key"].tolist()
                }
                if len(related_keys) > 1:
                    conflicting_source_keys.update(related_keys)

        for source_key, group in candidate_frame.groupby(
            "source_series_key",
            sort=False,
            dropna=False,
        ):
            reasons: list[str] = []
            if len(str(source_key)) > 80:
                reasons.append("SERIES_ID_TOO_LONG")
            if str(source_key) in conflicting_source_keys:
                reasons.append("URL_TO_SERIES_KEY_CONFLICT")
            for column in (
                "league",
                "year",
                "split",
                "playoffs",
                "team_pair",
                "best_of",
            ):
                if len(group[column].drop_duplicates()) != 1:
                    reasons.append(f"SERIES_{column.upper()}_CONFLICT")

            game_numbers = [int(value) for value in group["game_number"]]
            if len(game_numbers) != len(set(game_numbers)):
                reasons.append("DUPLICATE_SERIES_GAME_NUMBER")
            if any(value < 1 for value in game_numbers):
                reasons.append("INVALID_SERIES_GAME_NUMBER")
            if game_numbers and sorted(game_numbers) != list(
                range(1, max(game_numbers) + 1)
            ):
                reasons.append("NON_CONTIGUOUS_SERIES_GAME_NUMBER")
            best_of_values = group["best_of"].drop_duplicates().tolist()
            if best_of_values and any(
                value > int(best_of_values[0]) for value in game_numbers
            ):
                reasons.append("GAME_NUMBER_EXCEEDS_EXPLICIT_BEST_OF")

            ordered = group.sort_values("game_number", kind="stable")
            dates = ordered["date"].tolist()
            if any(later < earlier for earlier, later in zip(dates, dates[1:])):
                reasons.append("SERIES_DATE_ORDER_CONFLICT")

            non_missing_url_keys = {
                str(value)
                for value in group["url_series_key"].tolist()
                if not _is_missing(value)
            }
            if len(non_missing_url_keys) > 1:
                reasons.append("URL_TO_SERIES_KEY_CONFLICT")

            status = SERIES_READY if not reasons else SERIES_BLOCKED
            reason = "SOURCE_SERIES_AND_BEST_OF_EXPLICIT"
            if reasons:
                reason = ",".join(sorted(set(reasons)))
            diagnostics.append(
                {
                    "source_key": str(source_key),
                    "status": status,
                    "reason": reason,
                    "detail": f"games={len(group)}",
                }
            )

            for gameid in group["gameid"].tolist():
                assignments.append(
                    {
                        "gameid": str(gameid),
                        "series_id": (
                            str(source_key) if status == SERIES_READY else pd.NA
                        ),
                        "series_status": status,
                        "series_reason": reason,
                    }
                )

            if status == SERIES_READY:
                first = group.iloc[0]
                series_records.append(
                    {
                        "series_id": str(source_key),
                        "source_series_key": str(source_key),
                        "league": first["league"],
                        "year": first["year"],
                        "split": first["split"],
                        "playoffs": first["playoffs"],
                        "best_of": int(first["best_of"]),
                    }
                )

    for row in metadata_rejected.itertuples(index=False):
        diagnostics.append(
            {
                "source_key": str(row.source_key),
                "status": SERIES_BLOCKED,
                "reason": str(row.reason),
                "detail": str(row.detail),
            }
        )
    if games.empty:
        diagnostics.append(
            {
                "source_key": "oracle_source",
                "status": SERIES_BLOCKED,
                "reason": "NO_VALID_GAME_METADATA",
                "detail": "No valid source game remains for series analysis.",
            }
        )

    assignment_frame = _records_frame(assignments, _SERIES_ASSIGNMENT_COLUMNS)
    if not assignment_frame.empty:
        assignment_frame = assignment_frame.drop_duplicates(
            subset=["gameid"],
            keep="last",
        ).reset_index(drop=True)
    diagnostic_frame = _records_frame(
        diagnostics,
        _SERIES_DIAGNOSTIC_COLUMNS,
    )
    series_frame = _records_frame(series_records, _SERIES_RECORD_COLUMNS)
    overall_status = SERIES_BLOCKED
    if (
        not games.empty
        and not assignment_frame.empty
        and not series_frame.empty
        and not bool(diagnostic_frame["status"].eq(SERIES_BLOCKED).any())
    ):
        overall_status = SERIES_READY

    return OracleSeriesAnalysis(
        status=overall_status,
        series_records=series_frame,
        diagnostics=diagnostic_frame,
        game_assignments=assignment_frame,
    )


def _unique_source_names(
    dataframe: pd.DataFrame,
    *,
    id_column: str,
    name_column: str,
    entity: str,
    maximum: int,
) -> tuple[dict[str, str], list[dict[str, str]]]:
    names: dict[str, str] = {}
    issues: list[dict[str, str]] = []
    eligible = dataframe.loc[~dataframe[id_column].map(_is_missing)]
    for source_id, group in eligible.groupby(id_column, sort=False, dropna=False):
        cleaned_names = {
            name
            for value in group[name_column].tolist()
            if (name := _text_or_none(value)) is not None
        }
        canonical_names = {canonical_key(name) for name in cleaned_names}
        if not cleaned_names:
            issues.append(
                _issue(entity, source_id, "MISSING_SOURCE_NAME", name_column)
            )
            continue
        if len(canonical_names) != 1 or len(cleaned_names) != 1:
            issues.append(
                _issue(
                    entity,
                    source_id,
                    "SOURCE_NAME_CONFLICT",
                    repr(sorted(cleaned_names)),
                )
            )
            continue
        name = next(iter(cleaned_names))
        if len(name) > maximum:
            issues.append(
                _issue(entity, source_id, "SOURCE_NAME_TOO_LONG", str(len(name)))
            )
            continue
        names[str(source_id)] = name
    return names, issues


def _snapshot_index(
    dataframe: pd.DataFrame,
    key_column: str,
) -> dict[str, dict[str, object]]:
    if dataframe.empty:
        return {}
    if key_column not in dataframe.columns:
        raise ValueError(f"Target snapshot is missing column: {key_column}")
    if bool(dataframe[key_column].map(_is_missing).any()):
        raise ValueError(f"Target snapshot has missing {key_column} values.")
    if bool(dataframe.duplicated(subset=[key_column]).any()):
        raise ValueError(f"Target snapshot has duplicate {key_column} values.")
    return {
        str(row[key_column]): row.to_dict()
        for _, row in dataframe.iterrows()
    }


def _snapshot_source_index(
    dataframe: pd.DataFrame,
    *,
    target_id_column: str,
    source_id_column: str,
) -> dict[str, str]:
    if dataframe.empty:
        return {}
    required = {target_id_column, source_id_column}
    if not required <= set(dataframe.columns):
        missing = ", ".join(sorted(required - set(dataframe.columns)))
        raise ValueError(f"Target snapshot is missing source-ID columns: {missing}")

    index: dict[str, str] = {}
    for row in dataframe.itertuples(index=False):
        source_id = getattr(row, source_id_column)
        if _is_missing(source_id):
            continue
        source_key = str(source_id)
        target_id = str(getattr(row, target_id_column))
        previous = index.get(source_key)
        if previous is not None and previous != target_id:
            raise ValueError(
                f"Target snapshot maps {source_id_column}={source_key} "
                "to multiple target IDs."
            )
        index[source_key] = target_id
    return index


def _build_team_records(
    identities: OracleIdentityResult,
    snapshot: OracleTargetSnapshot,
) -> tuple[pd.DataFrame, dict[str, str], list[dict[str, str]]]:
    source = identities.team_participations
    names, name_issues = _unique_source_names(
        source,
        id_column="resolved_oracle_team_id",
        name_column="source_teamname",
        entity="team",
        maximum=150,
    )
    issues: list[dict[str, str]] = []
    name_issues_by_id: dict[str, list[dict[str, str]]] = {}
    for issue in name_issues:
        name_issues_by_id.setdefault(issue["source_key"], []).append(issue)
    existing = _snapshot_index(snapshot.teams, "team_id")
    existing_by_source = _snapshot_source_index(
        snapshot.teams,
        target_id_column="team_id",
        source_id_column="oracle_team_id",
    )
    source_to_target: dict[str, str] = {}
    records: list[dict[str, object]] = []

    for source_id, group in source.loc[
        ~source["resolved_oracle_team_id"].map(_is_missing)
    ].groupby("resolved_oracle_team_id", sort=False, dropna=False):
        oracle_id = str(source_id)
        statuses = set(group["team_target_status"].astype(str).tolist())
        target_ids = {
            str(value)
            for value in group["target_team_id"].tolist()
            if not _is_missing(value)
        }
        if len(statuses) != 1:
            issues.append(
                _issue("team", oracle_id, "TARGET_STATUS_CONFLICT", repr(statuses))
            )
            continue
        status = next(iter(statuses))
        if status == TARGET_CONFLICT:
            issues.append(
                _issue("team", oracle_id, "TARGET_ORACLE_ID_CONFLICT", "")
            )
            continue
        if status == TARGET_EXISTING:
            if len(target_ids) != 1:
                issues.append(
                    _issue("team", oracle_id, "TARGET_ID_MISSING", repr(target_ids))
                )
                continue
            target_id = next(iter(target_ids))
            target = existing.get(target_id)
            if target is None:
                issues.append(
                    _issue("team", oracle_id, "TARGET_SNAPSHOT_MISSING", target_id)
                )
                continue
            if existing_by_source.get(oracle_id) != target_id:
                issues.append(
                    _issue(
                        "team",
                        oracle_id,
                        "TARGET_ORACLE_ID_MISMATCH",
                        target_id,
                    )
                )
                continue
            record = {
                column: target.get(column) for column in TEAM_COLUMNS
            }
        elif status == TARGET_NEW_REQUIRED:
            known_target_id = existing_by_source.get(oracle_id)
            if known_target_id is not None:
                target_id = known_target_id
                record = {
                    column: existing[target_id].get(column)
                    for column in TEAM_COLUMNS
                }
            else:
                target_id = oracle_id
                occupied = existing.get(target_id)
                if occupied is None:
                    if oracle_id not in names:
                        issues.extend(name_issues_by_id.get(oracle_id, ()))
                        continue
                    record = {
                        "team_id": target_id,
                        "oracle_team_id": oracle_id,
                        "canonical_name": names[oracle_id],
                        "display_name": names[oracle_id],
                        "logo_file": None,
                    }
                elif str(occupied.get("oracle_team_id")) != oracle_id:
                    issues.append(
                        _issue(
                            "team",
                            oracle_id,
                            "TARGET_PRIMARY_KEY_COLLISION",
                            target_id,
                        )
                    )
                    continue
                else:
                    record = {
                        column: occupied.get(column) for column in TEAM_COLUMNS
                    }
        else:
            issues.append(
                _issue("team", oracle_id, "TARGET_STATUS_UNSUPPORTED", status)
            )
            continue

        source_to_target[oracle_id] = target_id
        records.append(record)

    return _records_frame(records, TEAM_COLUMNS), source_to_target, issues


def _build_player_records(
    identities: OracleIdentityResult,
    snapshot: OracleTargetSnapshot,
) -> tuple[pd.DataFrame, dict[str, str], list[dict[str, str]]]:
    source = identities.player_rows
    names, name_issues = _unique_source_names(
        source,
        id_column="resolved_oracle_player_id",
        name_column="playername",
        entity="player",
        maximum=120,
    )
    issues: list[dict[str, str]] = []
    name_issues_by_id: dict[str, list[dict[str, str]]] = {}
    for issue in name_issues:
        name_issues_by_id.setdefault(issue["source_key"], []).append(issue)
    existing = _snapshot_index(snapshot.players, "player_id")
    existing_by_source = _snapshot_source_index(
        snapshot.players,
        target_id_column="player_id",
        source_id_column="oracle_player_id",
    )
    source_to_target: dict[str, str] = {}
    records: list[dict[str, object]] = []

    for source_id, group in source.loc[
        ~source["resolved_oracle_player_id"].map(_is_missing)
    ].groupby("resolved_oracle_player_id", sort=False, dropna=False):
        oracle_id = str(source_id)
        statuses = set(group["player_target_status"].astype(str).tolist())
        target_ids = {
            str(value)
            for value in group["target_player_id"].tolist()
            if not _is_missing(value)
        }
        if len(statuses) != 1:
            issues.append(
                _issue("player", oracle_id, "TARGET_STATUS_CONFLICT", repr(statuses))
            )
            continue
        status = next(iter(statuses))
        if status == TARGET_CONFLICT:
            issues.append(
                _issue("player", oracle_id, "TARGET_ORACLE_ID_CONFLICT", "")
            )
            continue
        if status == TARGET_EXISTING:
            if len(target_ids) != 1:
                issues.append(
                    _issue("player", oracle_id, "TARGET_ID_MISSING", repr(target_ids))
                )
                continue
            target_id = next(iter(target_ids))
            target = existing.get(target_id)
            if target is None:
                issues.append(
                    _issue("player", oracle_id, "TARGET_SNAPSHOT_MISSING", target_id)
                )
                continue
            if existing_by_source.get(oracle_id) != target_id:
                issues.append(
                    _issue(
                        "player",
                        oracle_id,
                        "TARGET_ORACLE_ID_MISMATCH",
                        target_id,
                    )
                )
                continue
            record = {
                column: target.get(column) for column in PLAYER_COLUMNS
            }
        elif status == TARGET_NEW_REQUIRED:
            known_target_id = existing_by_source.get(oracle_id)
            if known_target_id is not None:
                target_id = known_target_id
                record = {
                    column: existing[target_id].get(column)
                    for column in PLAYER_COLUMNS
                }
            else:
                target_id = oracle_id
                occupied = existing.get(target_id)
                if occupied is None:
                    if oracle_id not in names:
                        issues.extend(name_issues_by_id.get(oracle_id, ()))
                        continue
                    record = {
                        "player_id": target_id,
                        "oracle_player_id": oracle_id,
                        "canonical_name": names[oracle_id],
                        "display_name": names[oracle_id],
                        "photo_file": None,
                    }
                elif str(occupied.get("oracle_player_id")) != oracle_id:
                    issues.append(
                        _issue(
                            "player",
                            oracle_id,
                            "TARGET_PRIMARY_KEY_COLLISION",
                            target_id,
                        )
                    )
                    continue
                else:
                    record = {
                        column: occupied.get(column) for column in PLAYER_COLUMNS
                    }
        else:
            issues.append(
                _issue("player", oracle_id, "TARGET_STATUS_UNSUPPORTED", status)
            )
            continue

        source_to_target[oracle_id] = target_id
        records.append(record)

    return _records_frame(records, PLAYER_COLUMNS), source_to_target, issues


def _stage_name(split: object, playoffs: int) -> str | None:
    split_name = _text_or_none(split)
    if split_name is None:
        return None
    return f"{split_name} Playoffs" if playoffs == 1 else split_name


def _build_context_records(
    games: pd.DataFrame,
) -> tuple[
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
    dict[tuple[str, int], str],
    dict[tuple[str, int, str | None, int], str],
    list[dict[str, str]],
]:
    patches: list[dict[str, object]] = []
    tournaments: list[dict[str, object]] = []
    stages: list[dict[str, object]] = []
    issues: list[dict[str, str]] = []
    tournament_ids: dict[tuple[str, int], str] = {}
    stage_ids: dict[tuple[str, int, str | None, int], str] = {}

    for patch in games["patch"].drop_duplicates().tolist():
        patch_text = str(patch)
        patches.append({"patch_id": patch_text, "patch_name": patch_text})

    contexts = games[["league", "year", "split", "playoffs"]].drop_duplicates()
    for row in contexts.itertuples(index=False):
        league = _text_or_none(row.league)
        season = int(row.year)
        playoffs = int(row.playoffs)
        split = _text_or_none(row.split)
        source_key = f"{league}|{season}|{split}|{playoffs}"
        if league is None or len(league) > 150:
            issues.append(
                _issue("tournament", source_key, "INVALID_LEAGUE", str(row.league))
            )
            continue
        if playoffs not in {0, 1}:
            issues.append(
                _issue("tournament_stage", source_key, "INVALID_PLAYOFFS", str(playoffs))
            )
            continue
        stage_name = _stage_name(split, playoffs)
        if stage_name is None or len(stage_name) > 100:
            issues.append(
                _issue(
                    "tournament_stage",
                    source_key,
                    "INSUFFICIENT_STAGE_CONTEXT",
                    "split is missing or the stage name exceeds 100 characters",
                )
            )
            continue

        tournament_key = (league, season)
        tournament_id = tournament_ids.get(tournament_key)
        if tournament_id is None:
            tournament_id = _stable_id(
                "oracle:tournament:",
                canonical_key(league),
                season,
            )
            tournament_ids[tournament_key] = tournament_id
            tournaments.append(
                {
                    "tournament_id": tournament_id,
                    "name": league,
                    "region": None,
                    "season": season,
                }
            )

        stage_key = (league, season, split, playoffs)
        if stage_key in stage_ids:
            continue
        stage_id = _stable_id(
            "oracle:stage:",
            tournament_id,
            split,
            playoffs,
        )
        stage_ids[stage_key] = stage_id
        stages.append(
            {
                "stage_id": stage_id,
                "tournament_id": tournament_id,
                "name": stage_name,
            }
        )

    return (
        _records_frame(patches, GAME_PATCH_COLUMNS),
        _records_frame(tournaments, TOURNAMENT_COLUMNS),
        _records_frame(stages, TOURNAMENT_STAGE_COLUMNS),
        tournament_ids,
        stage_ids,
        issues,
    )


def _identity_issues(
    identities: OracleIdentityResult,
) -> list[dict[str, str]]:
    issues: list[dict[str, str]] = []
    teams = identities.team_participations
    unresolved_teams = teams.loc[
        teams["team_resolution_method"].eq(UNRESOLVED)
    ]
    for row in unresolved_teams.itertuples(index=False):
        issues.append(
            _issue(
                "team_participation",
                f"{row.gameid}|{row.side}",
                str(row.team_resolution_reason),
                repr(row.team_resolution_candidates),
            )
        )

    players = identities.player_rows
    unresolved_players = players.loc[
        players["player_resolution_method"].eq(UNRESOLVED)
    ]
    for row in unresolved_players.itertuples(index=True):
        issues.append(
            _issue(
                "player_row",
                f"{row.gameid}|{row.side}|{row.position}|{row.Index}",
                str(row.player_resolution_reason),
                repr(row.player_resolution_candidates),
            )
        )
    return issues


def _unmapped_champions(identities: OracleIdentityResult) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    players = identities.player_rows
    unmapped = players.loc[~players["champion_mapping_status"].eq(CHAMPION_MAPPED)]
    for row in unmapped.itertuples(index=False):
        rows.append(
            {
                "gameid": row.gameid,
                "side": row.side,
                "position": row.position,
                "champion": row.champion,
                "reason": row.champion_mapping_reason,
            }
        )
    return _records_frame(rows, UNMAPPED_CHAMPION_COLUMNS)


def _analyze_game_lineups(
    games: pd.DataFrame,
    identities: OracleIdentityResult,
    *,
    player_targets: dict[str, str],
) -> tuple[dict[str, tuple[str, ...]], list[dict[str, str]]]:
    """Validate a complete lineup before emitting any row for its game."""
    player_groups = {
        str(gameid): group
        for gameid, group in identities.player_rows.groupby(
            "gameid",
            sort=False,
            dropna=False,
        )
    }
    empty_group = identities.player_rows.iloc[0:0]
    blocking_by_game: dict[str, tuple[str, ...]] = {}
    diagnostics: list[dict[str, str]] = []

    for gameid_value in games["gameid"].tolist():
        gameid = str(gameid_value)
        group = player_groups.get(gameid, empty_group)
        game_codes: set[str] = set()
        valid_rows: list[tuple[str, str, str, str]] = []

        for row in group.itertuples(index=True):
            source_key = f"{gameid}|{row.side}|{row.position}|{row.Index}"
            row_codes: set[str] = set()
            side_text = _text_or_none(row.side)
            role_text = _text_or_none(row.position)
            side = SIDE_MAP.get((side_text or "").casefold())
            role = ROLE_MAP.get((role_text or "").casefold())

            if side is None:
                row_codes.add("INVALID_SIDE")
            if role is None:
                row_codes.add("INVALID_ROLE")

            participant_value = row.participantid
            participant_id = (
                None
                if _is_missing(participant_value)
                else str(participant_value)
            )
            if participant_id is None:
                row_codes.add("MISSING_PARTICIPANT_ID")

            oracle_player_id = row.resolved_oracle_player_id
            if _is_missing(oracle_player_id):
                if _is_missing(row.playerid):
                    row_codes.add("MISSING_PLAYER_ID")
                row_codes.add(
                    _text_or_none(row.player_resolution_reason)
                    or "PLAYER_ID_UNRESOLVED"
                )
                player_id = None
            else:
                player_id = player_targets.get(str(oracle_player_id))
                if player_id is None:
                    row_codes.add("PLAYER_TARGET_UNRESOLVED")

            champion_mapped = (
                row.champion_mapping_status == CHAMPION_MAPPED
                and not _is_missing(row.champion_id)
            )
            if not champion_mapped:
                row_codes.add("CHAMPION_UNMAPPED")
                champion_reason = _text_or_none(row.champion_mapping_reason)
                if champion_reason is not None:
                    row_codes.add(champion_reason)

            if row_codes:
                game_codes.update(row_codes)
                diagnostics.extend(
                    _issue(
                        "game_player",
                        source_key,
                        code,
                        "Lineup preflight failed for this source row.",
                    )
                    for code in sorted(row_codes)
                )
                continue

            if (
                side is None
                or role is None
                or player_id is None
                or participant_id is None
            ):
                raise AssertionError("Validated lineup row lost a required value.")
            valid_rows.append((side, role, player_id, participant_id))

        if len(valid_rows) != 10:
            game_codes.add("GAME_REQUIRES_TEN_RESOLVED_PLAYERS")
        if len({row[2] for row in valid_rows}) != 10:
            game_codes.add("GAME_REQUIRES_TEN_UNIQUE_PLAYERS")
        if len({row[3] for row in valid_rows}) != 10:
            game_codes.add("DUPLICATE_GAME_PARTICIPANT_ID")

        for side in ("BLUE", "RED"):
            side_rows = [row for row in valid_rows if row[0] == side]
            roles = [row[1] for row in side_rows]
            if (
                len(side_rows) != 5
                or set(roles) != _EXPECTED_ROLES
                or len(roles) != len(set(roles))
            ):
                game_codes.add("TEAM_ROLE_SET_INCOMPLETE")
                diagnostics.append(
                    _issue(
                        "game_player",
                        f"{gameid}|{side}",
                        "TEAM_ROLE_SET_INCOMPLETE",
                        json.dumps(
                            {
                                "observed_roles": sorted(set(roles)),
                                "required_roles": sorted(_EXPECTED_ROLES),
                                "row_count": len(side_rows),
                            },
                            sort_keys=True,
                        ),
                    )
                )

        if game_codes:
            blocking_by_game[gameid] = tuple(sorted(game_codes))

    return blocking_by_game, diagnostics


def _build_game_records(
    games: pd.DataFrame,
    identities: OracleIdentityResult,
    *,
    team_targets: dict[str, str],
    stage_ids: dict[tuple[str, int, str | None, int], str],
    series_analysis: OracleSeriesAnalysis,
    available_series_ids: set[str],
    lineup_reasons_by_game: dict[str, tuple[str, ...]],
) -> tuple[
    pd.DataFrame,
    pd.DataFrame,
    set[str],
    list[dict[str, str]],
]:
    team_source = identities.team_participations
    result_rows: list[dict[str, object]] = []
    team_records: list[dict[str, object]] = []
    accepted_games: set[str] = set()
    rejected: list[dict[str, str]] = []
    assignments = {
        str(row.gameid): str(row.series_id)
        for row in series_analysis.game_assignments.itertuples(index=False)
        if row.series_status == SERIES_READY
        and not _is_missing(row.series_id)
    }
    team_groups = {
        str(gameid): group
        for gameid, group in team_source.groupby(
            "gameid",
            sort=False,
            dropna=False,
        )
    }
    empty_team_group = team_source.iloc[0:0]

    # The normalized source result is joined outside this helper by adding a
    # temporary ``source_result`` column to a copied team resolution frame.
    if "source_result" not in team_source.columns:
        raise ValueError("Team resolutions are missing source_result for game transform.")

    for game in games.itertuples(index=False):
        gameid = str(game.gameid)
        group = team_groups.get(gameid, empty_team_group)
        normalized_rows: list[tuple[str, str, int]] = []
        reasons: list[str] = []
        for row in group.itertuples(index=False):
            side_key = _text_or_none(row.side)
            side = SIDE_MAP.get((side_key or "").casefold())
            oracle_team_id = row.resolved_oracle_team_id
            target_team_id = (
                None
                if _is_missing(oracle_team_id)
                else team_targets.get(str(oracle_team_id))
            )
            result = row.source_result
            if side is None:
                reasons.append("INVALID_SIDE")
                continue
            if target_team_id is None:
                reasons.append("TEAM_UNRESOLVED")
                continue
            if _is_missing(result) or int(result) not in {0, 1}:
                reasons.append("INVALID_TEAM_RESULT")
                continue
            normalized_rows.append((side, target_team_id, int(result)))

        sides = [row[0] for row in normalized_rows]
        team_ids = [row[1] for row in normalized_rows]
        winners = [row[1] for row in normalized_rows if row[2] == 1]
        if sorted(sides) != ["BLUE", "RED"]:
            reasons.append("GAME_REQUIRES_BLUE_AND_RED")
        if len(set(team_ids)) != 2:
            reasons.append("GAME_REQUIRES_TWO_TEAMS")
        if len(winners) != 1:
            reasons.append("GAME_REQUIRES_ONE_WINNER")

        stage_key = (
            _text_or_none(game.league),
            int(game.year),
            _text_or_none(game.split),
            int(game.playoffs),
        )
        stage_id = stage_ids.get(stage_key)
        if stage_id is None:
            reasons.append("STAGE_UNRESOLVED")

        assigned_series_id = assignments.get(gameid)
        series_id = (
            assigned_series_id
            if assigned_series_id in available_series_ids
            else None
        )
        direct_stage_id = None if series_id is not None else stage_id
        has_exactly_one_parent = (series_id is None) != (
            direct_stage_id is None
        )
        if not has_exactly_one_parent:
            reasons.append("GAME_PARENT_UNRESOLVED")

        lineup_reasons = lineup_reasons_by_game.get(gameid, ())
        primary_reason: str | None = None
        if lineup_reasons:
            primary_reason = "GAME_LINEUP_INCOMPLETE"
        elif reasons:
            primary_reason = "GAME_DEPENDENCY_INVALID"

        if primary_reason is not None:
            rejected.append(
                _issue(
                    "game",
                    gameid,
                    primary_reason,
                    ",".join(sorted(set(reasons) | set(lineup_reasons))),
                )
            )
            continue

        accepted_games.add(gameid)
        result_rows.append(
            {
                "game_id": gameid,
                "series_id": series_id,
                "stage_id": direct_stage_id,
                "patch_id": str(game.patch),
                "game_number": int(game.game),
                "scheduled_at": None,
                "started_at": None,
                "ended_at": None,
                "winner_team_id": winners[0],
            }
        )
        for side, target_team_id, _ in normalized_rows:
            team_records.append(
                {
                    "game_id": gameid,
                    "team_id": target_team_id,
                    "side": side,
                    "confirmation_status": SOURCE_REPORTED,
                }
            )

    game_frame = _records_frame(result_rows, GAME_COLUMNS)
    team_frame = _records_frame(team_records, GAME_TEAM_COLUMNS)
    if len(team_frame) != 2 * len(accepted_games):
        raise ValueError("Accepted games must emit two game_team rows each.")
    if not team_frame.empty:
        if bool(team_frame.duplicated(subset=["game_id", "side"]).any()):
            raise ValueError("Accepted games contain duplicate game-side rows.")
        if bool(team_frame.duplicated(subset=["game_id", "team_id"]).any()):
            raise ValueError("Accepted games contain duplicate game-team rows.")

    return game_frame, team_frame, accepted_games, rejected


def _attach_team_results(
    core_data: OracleCoreData,
    identities: OracleIdentityResult,
) -> OracleIdentityResult:
    team_rows = core_data.team_rows[["gameid", "side", "result"]].copy()
    if bool(team_rows.duplicated(subset=["gameid", "side"]).any()):
        raise ValueError("Oracle team rows contain duplicate game-side results.")
    result_lookup = team_rows.set_index(["gameid", "side"])["result"]
    teams = identities.team_participations.copy().join(
        result_lookup.rename("source_result"),
        on=["gameid", "side"],
        how="left",
        validate="one_to_one",
    )
    return OracleIdentityResult(
        team_participations=teams,
        player_rows=identities.player_rows.copy(),
    )


def _build_game_player_records(
    identities: OracleIdentityResult,
    *,
    accepted_games: set[str],
    player_targets: dict[str, str],
) -> pd.DataFrame:
    records: list[dict[str, object]] = []
    for row in identities.player_rows.itertuples(index=False):
        gameid = str(row.gameid)
        if gameid not in accepted_games:
            continue
        side_text = _text_or_none(row.side)
        role_text = _text_or_none(row.position)
        side = SIDE_MAP.get((side_text or "").casefold())
        role = ROLE_MAP.get((role_text or "").casefold())
        oracle_player_id = row.resolved_oracle_player_id
        player_id = (
            None
            if _is_missing(oracle_player_id)
            else player_targets.get(str(oracle_player_id))
        )
        champion_id = row.champion_id
        champion_mapped = (
            row.champion_mapping_status == CHAMPION_MAPPED
            and not _is_missing(champion_id)
        )
        if (
            side is None
            or role is None
            or player_id is None
            or not champion_mapped
        ):
            raise ValueError(
                "Accepted game failed lineup preflight: "
                f"{gameid}|{row.side}|{row.position}"
            )
        records.append(
            {
                "game_id": gameid,
                "side": side,
                "player_id": player_id,
                "role": role,
                "champion_id": str(champion_id),
                "confirmation_status": SOURCE_REPORTED,
            }
        )

    frame = _records_frame(records, GAME_PLAYER_COLUMNS)
    if len(frame) != 10 * len(accepted_games):
        raise ValueError("Accepted games must emit ten game_player rows each.")
    if not frame.empty:
        if bool(
            frame.duplicated(subset=["game_id", "side", "role"]).any()
        ):
            raise ValueError("Accepted games contain duplicate side-role rows.")
        if bool(frame["champion_id"].isna().any()):
            raise ValueError("Accepted games contain NULL champion_id.")
        unique_players = frame.groupby("game_id")["player_id"].nunique()
        if bool(unique_players.ne(10).any()):
            raise ValueError("Accepted games require ten unique players.")
    return frame


def _game_dependency_cascade_issues(
    identities: OracleIdentityResult,
    *,
    accepted_games: set[str],
) -> list[dict[str, str]]:
    issues: list[dict[str, str]] = []
    for row in identities.team_participations.itertuples(index=True):
        gameid = str(row.gameid)
        if gameid in accepted_games:
            continue
        issues.append(
            _issue(
                "game_team",
                f"{gameid}|{row.side}|{row.Index}",
                "GAME_TEAM_BLOCKED_BY_GAME",
                "The parent game was not emitted.",
            )
        )
    for row in identities.player_rows.itertuples(index=True):
        gameid = str(row.gameid)
        if gameid in accepted_games:
            continue
        issues.append(
            _issue(
                "game_player",
                f"{gameid}|{row.side}|{row.position}|{row.Index}",
                "GAME_PLAYER_BLOCKED_BY_GAME",
                "The parent game was not emitted.",
            )
        )
    return issues


def _artifact_value(
    group: pd.DataFrame,
    column: str,
    *,
    calendar_date: bool = False,
    integer: bool = False,
) -> object:
    values: list[object] = []
    for value in group[column].tolist():
        if _is_missing(value):
            continue
        if calendar_date:
            rendered: object = pd.Timestamp(value).date().isoformat()
        elif integer:
            rendered = int(value)
        else:
            rendered = _text_or_none(value)
        if rendered is not None and rendered not in values:
            values.append(rendered)

    if not values:
        return None
    if len(values) == 1:
        return values[0]
    return json.dumps(values, ensure_ascii=False, default=str)


def _artifact_team_name(group: pd.DataFrame, side: str) -> object:
    normalized_sides = group["side"].astype("string").str.casefold()
    side_group = group.loc[
        normalized_sides.eq(side.casefold()).fillna(False)
    ]
    return _artifact_value(side_group, "teamname")


def _secondary_codes(detail: object) -> list[str]:
    text = _text_or_none(detail)
    if text is None:
        return []
    return sorted({code.strip() for code in text.split(",") if code.strip()})


def _build_rejected_game_records(
    core_data: OracleCoreData,
    *,
    accepted_games: set[str],
    primary_game_issues: list[dict[str, str]],
) -> pd.DataFrame:
    """Build one additive primary-disposition row per rejected source game."""
    source = core_data.dataframe
    valid_source = source.loc[~source["gameid"].map(_is_missing)]
    groups = {
        str(gameid): group
        for gameid, group in valid_source.groupby(
            "gameid",
            sort=False,
            dropna=False,
        )
    }
    source_game_ids = set(groups)
    primary_by_game: dict[str, dict[str, str]] = {}
    for issue in primary_game_issues:
        gameid = str(issue["source_key"])
        if gameid not in source_game_ids:
            continue
        if gameid in primary_by_game:
            raise ValueError(f"Game has multiple primary rejections: {gameid}")
        primary_by_game[gameid] = issue

    rejected_game_ids = set(primary_by_game)
    overlap = accepted_games & rejected_game_ids
    if overlap:
        raise ValueError(
            "Games cannot be both accepted and rejected: "
            + ", ".join(sorted(overlap)[:20])
        )

    unclassified = source_game_ids - accepted_games - rejected_game_ids
    if unclassified:
        raise ValueError(
            "Source games lack a final disposition: "
            + ", ".join(sorted(unclassified)[:20])
        )

    rows: list[dict[str, object]] = []
    for gameid in sorted(rejected_game_ids):
        group = groups[gameid]
        issue = primary_by_game[gameid]
        detail = issue["detail"]
        rows.append(
            {
                "gameid": gameid,
                "primary_reason": issue["reason"],
                "secondary_reasons": json.dumps(
                    _secondary_codes(detail),
                    ensure_ascii=False,
                ),
                "league": _artifact_value(group, "league"),
                "source_year": _artifact_value(group, "year", integer=True),
                "calendar_date": _artifact_value(
                    group,
                    "date",
                    calendar_date=True,
                ),
                "patch": _artifact_value(group, "patch"),
                "split": _artifact_value(group, "split"),
                "datacompleteness": _artifact_value(
                    group,
                    "datacompleteness",
                ),
                "blue_team": _artifact_team_name(group, "Blue"),
                "red_team": _artifact_team_name(group, "Red"),
                "detail": detail,
            }
        )

    return _records_frame(rows, REJECTED_GAME_COLUMNS)


def _build_series_targets(
    analysis: OracleSeriesAnalysis,
    stage_ids: dict[tuple[str, int, str | None, int], str],
) -> tuple[pd.DataFrame, list[dict[str, str]]]:
    records: list[dict[str, object]] = []
    issues: list[dict[str, str]] = []
    for row in analysis.series_records.itertuples(index=False):
        key = (
            _text_or_none(row.league),
            int(row.year),
            _text_or_none(row.split),
            int(row.playoffs),
        )
        stage_id = stage_ids.get(key)
        if stage_id is None:
            issues.append(
                _issue(
                    "series",
                    row.series_id,
                    "SERIES_STAGE_UNRESOLVED",
                    repr(key),
                )
            )
            continue
        records.append(
            {
                "series_id": str(row.series_id),
                "stage_id": stage_id,
                "best_of": int(row.best_of),
            }
        )
    return _records_frame(records, SERIES_COLUMNS), issues


def _missing_equal(left: object, right: object) -> bool:
    if _is_missing(left) and _is_missing(right):
        return True
    if _is_missing(left) or _is_missing(right):
        return False
    return left == right


def _reconciliation_value_equal(
    *,
    table: str,
    column: str,
    candidate: object,
    current: object,
) -> bool:
    """Compare with the protected apply module's preserve-on-null contract."""
    preserved = PRESERVE_ON_NULL_COLUMNS.get(table, frozenset())
    if column in preserved and _is_missing(candidate):
        return True
    return _missing_equal(candidate, current)


def _game_team_side_index(
    dataframe: pd.DataFrame,
    *,
    label: str,
) -> dict[tuple[str, str], str]:
    if dataframe.empty:
        return {}
    required = {"game_id", "team_id", "side"}
    if not required <= set(dataframe.columns):
        missing = ", ".join(sorted(required - set(dataframe.columns)))
        raise ValueError(f"game_team {label} is missing columns: {missing}")
    if any(
        _is_missing(value)
        for value in dataframe.loc[:, sorted(required)].to_numpy().ravel()
    ):
        raise ValueError(f"game_team {label} has missing alternate-key values.")
    if bool(dataframe.duplicated(subset=["game_id", "team_id"]).any()):
        raise ValueError(
            f"game_team {label} has duplicate (game_id, team_id) values."
        )
    return {
        (str(row.game_id), str(row.team_id)): str(row.side)
        for row in dataframe.itertuples(index=False)
    }


def _record_actions(
    records: OracleTargetRecords,
    snapshot: OracleTargetSnapshot,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    candidate_team_sides = _game_team_side_index(
        records.game_teams,
        label="candidates",
    )
    existing_team_sides = _game_team_side_index(
        snapshot.game_teams,
        label="snapshot",
    )
    side_transitions = sorted(
        key
        for key, side in candidate_team_sides.items()
        if key in existing_team_sides and existing_team_sides[key] != side
    )
    if side_transitions:
        samples = ", ".join("|".join(key) for key in side_transitions[:5])
        raise ValueError(
            "game_team side transition conflicts with the alternate unique key: "
            + samples
        )

    specifications = (
        ("game_patch", records.game_patches, snapshot.game_patches, ("patch_id",)),
        (
            "tournament",
            records.tournaments,
            snapshot.tournaments,
            ("tournament_id",),
        ),
        (
            "tournament_stage",
            records.tournament_stages,
            snapshot.tournament_stages,
            ("stage_id",),
        ),
        ("series", records.series, snapshot.series, ("series_id",)),
        ("team", records.teams, snapshot.teams, ("team_id",)),
        ("player", records.players, snapshot.players, ("player_id",)),
        ("game", records.games, snapshot.games, ("game_id",)),
        (
            "game_team",
            records.game_teams,
            snapshot.game_teams,
            ("game_id", "side"),
        ),
        (
            "game_player",
            records.game_players,
            snapshot.game_players,
            ("game_id", "side", "role"),
        ),
    )
    actions: list[dict[str, str]] = []
    skipped: list[dict[str, str]] = []

    for table, candidate, existing, keys in specifications:
        if candidate.empty:
            continue
        if not set(keys) <= set(candidate.columns):
            raise ValueError(f"{table} candidates are missing reconciliation keys.")
        if bool(candidate.duplicated(subset=list(keys)).any()):
            raise ValueError(f"{table} candidates have duplicate reconciliation keys.")
        if any(
            _is_missing(value)
            for value in candidate.loc[:, list(keys)].to_numpy().ravel()
        ):
            raise ValueError(f"{table} candidates have missing reconciliation keys.")
        missing_snapshot_columns = sorted(set(candidate.columns) - set(existing.columns))
        if missing_snapshot_columns:
            raise ValueError(
                f"{table} snapshot is missing comparison columns: "
                + ", ".join(missing_snapshot_columns)
            )
        if existing.empty:
            existing_index: dict[tuple[str, ...], dict[str, object]] = {}
        else:
            if not set(keys) <= set(existing.columns):
                raise ValueError(f"{table} snapshot is missing reconciliation keys.")
            if any(
                _is_missing(value)
                for value in existing.loc[:, list(keys)].to_numpy().ravel()
            ):
                raise ValueError(
                    f"{table} snapshot has missing reconciliation keys."
                )
            if bool(existing.duplicated(subset=list(keys)).any()):
                raise ValueError(f"{table} snapshot has duplicate reconciliation keys.")
            existing_index = {
                tuple(str(row[key]) for key in keys): row.to_dict()
                for _, row in existing.iterrows()
            }

        for _, row in candidate.iterrows():
            key = tuple(str(row[column]) for column in keys)
            source_key = "|".join(key)
            current = existing_index.get(key)
            if current is None:
                action = "INSERT"
            else:
                unchanged = all(
                    _reconciliation_value_equal(
                        table=table,
                        column=column,
                        candidate=row[column],
                        current=current[column],
                    )
                    for column in candidate.columns
                )
                action = "SKIP" if unchanged else "UPDATE"
            actions.append(
                {"table": table, "source_key": source_key, "action": action}
            )
            if action == "SKIP":
                skipped.append(
                    _issue(table, source_key, "TARGET_UNCHANGED", "")
                )

    return (
        _records_frame(actions, ACTION_COLUMNS),
        _records_frame(skipped, ISSUE_COLUMNS),
    )


def transform_oracle_targets(
    core_data: OracleCoreData,
    identity_result: OracleIdentityResult,
    *,
    target_snapshot: OracleTargetSnapshot | None = None,
    series_analysis: OracleSeriesAnalysis | None = None,
) -> OracleDryRunResult:
    """Build nine target DataFrames without performing a database write."""

    snapshot = target_snapshot or OracleTargetSnapshot()
    analysis = series_analysis or analyze_series_evidence(
        core_data,
        identity_result,
    )
    games, metadata_rejected = _collapse_game_metadata(core_data)
    identities = _attach_team_results(core_data, identity_result)

    teams, team_targets, team_entity_issues = _build_team_records(
        identities,
        snapshot,
    )
    players, player_targets, player_entity_issues = _build_player_records(
        identities,
        snapshot,
    )
    lineup_reasons_by_game, lineup_issues = _analyze_game_lineups(
        games,
        identities,
        player_targets=player_targets,
    )
    (
        game_patches,
        tournaments,
        tournament_stages,
        _,
        stage_ids,
        context_issues,
    ) = _build_context_records(games)
    series, series_issues = _build_series_targets(analysis, stage_ids)
    available_series_ids = set(series["series_id"].astype(str).tolist())
    game_records, game_teams, accepted_games, game_issues = (
        _build_game_records(
            games,
            identities,
            team_targets=team_targets,
            stage_ids=stage_ids,
            series_analysis=analysis,
            available_series_ids=available_series_ids,
            lineup_reasons_by_game=lineup_reasons_by_game,
        )
    )
    game_players = _build_game_player_records(
        identities,
        accepted_games=accepted_games,
        player_targets=player_targets,
    )
    cascade_issues = _game_dependency_cascade_issues(
        identities,
        accepted_games=accepted_games,
    )

    records = OracleTargetRecords(
        game_patches=game_patches,
        tournaments=tournaments,
        tournament_stages=tournament_stages,
        series=series,
        teams=teams,
        players=players,
        games=game_records,
        game_teams=game_teams,
        game_players=game_players,
    )
    actions, skipped = _record_actions(records, snapshot)

    unresolved = _identity_issues(identities)
    for row in analysis.diagnostics.loc[
        analysis.diagnostics["status"].eq(SERIES_BLOCKED)
    ].itertuples(index=False):
        unresolved.append(
            _issue("series", row.source_key, str(row.reason), str(row.detail))
        )

    rejected = metadata_rejected.to_dict("records")
    rejected.extend(team_entity_issues)
    rejected.extend(player_entity_issues)
    rejected.extend(context_issues)
    rejected.extend(series_issues)
    rejected.extend(lineup_issues)
    rejected.extend(game_issues)
    rejected.extend(cascade_issues)

    primary_game_issues = metadata_rejected.to_dict("records")
    primary_game_issues.extend(game_issues)
    rejected_games = _build_rejected_game_records(
        core_data,
        accepted_games=accepted_games,
        primary_game_issues=primary_game_issues,
    )

    return OracleDryRunResult(
        records=records,
        unresolved_records=_records_frame(unresolved, ISSUE_COLUMNS),
        rejected_records=_records_frame(rejected, ISSUE_COLUMNS),
        skipped_records=skipped,
        unmapped_champions=_unmapped_champions(identities),
        series_analysis=analysis,
        actions=actions,
        source_counts={
            "source_rows": int(len(core_data.dataframe)),
            "player_rows": int(len(core_data.player_rows)),
            "team_rows": int(len(core_data.team_rows)),
            "distinct_games": int(core_data.dataframe["gameid"].nunique()),
        },
        rejected_games=rejected_games,
    )


def build_dry_run_summary(result: OracleDryRunResult) -> dict[str, object]:
    """Return dynamic reconciliation counts; no benchmark is hard-coded."""

    record_counts = {
        "game_patch": int(len(result.records.game_patches)),
        "tournament": int(len(result.records.tournaments)),
        "tournament_stage": int(len(result.records.tournament_stages)),
        "series": int(len(result.records.series)),
        "team": int(len(result.records.teams)),
        "player": int(len(result.records.players)),
        "game": int(len(result.records.games)),
        "game_team": int(len(result.records.game_teams)),
        "game_player": int(len(result.records.game_players)),
    }
    action_counts: dict[str, dict[str, int]] = {}
    for table in TARGET_TABLE_ORDER:
        table_actions = result.actions.loc[result.actions["table"].eq(table)]
        counts = table_actions["action"].value_counts()
        action_counts[table] = {
            "inserted_expected": int(counts.get("INSERT", 0)),
            "updated_expected": int(counts.get("UPDATE", 0)),
            "skipped": int(counts.get("SKIP", 0)),
        }

    unresolved_reasons = {
        str(key): int(value)
        for key, value in result.unresolved_records["reason"]
        .value_counts()
        .sort_index()
        .items()
    }
    rejected_reasons = {
        str(key): int(value)
        for key, value in result.rejected_records["reason"]
        .value_counts()
        .sort_index()
        .items()
    }
    metadata_details = {
        str(key): int(value)
        for key, value in result.rejected_records.loc[
            result.rejected_records["reason"].eq("GAME_METADATA_INVALID"),
            "detail",
        ]
        .value_counts()
        .sort_index()
        .items()
    }
    primary_rejection_reasons = {
        str(key): int(value)
        for key, value in result.rejected_games["primary_reason"]
        .value_counts()
        .sort_index()
        .items()
    }
    series_status_counts = {
        str(key): int(value)
        for key, value in result.series_analysis.game_assignments[
            "series_status"
        ]
        .value_counts()
        .sort_index()
        .items()
    }
    series_diagnostic_reasons = {
        str(key): int(value)
        for key, value in result.series_analysis.diagnostics["reason"]
        .value_counts()
        .sort_index()
        .items()
    }
    transformed_games = record_counts["game"]
    source_games = result.source_counts["distinct_games"]
    if transformed_games == 0:
        game_transform_status = GAME_TRANSFORM_BLOCKED
    elif transformed_games == source_games:
        game_transform_status = GAME_TRANSFORM_READY
    elif transformed_games < source_games:
        game_transform_status = GAME_TRANSFORM_PARTIAL
    else:
        raise ValueError(
            "Transformed game count exceeds the distinct source game count."
        )

    return {
        "mode": "DRY_RUN",
        **result.source_counts,
        "transformed_records": record_counts,
        "actions": action_counts,
        "skipped": int(len(result.skipped_records)),
        "unresolved": int(len(result.unresolved_records)),
        "unresolved_reason_counts": unresolved_reasons,
        "rejected": int(len(result.rejected_records)),
        "rejected_reason_counts": rejected_reasons,
        "primary_rejected_games": int(len(result.rejected_games)),
        "primary_rejection_reason_counts": primary_rejection_reasons,
        "game_metadata_detail_counts": metadata_details,
        "unmapped_champions": int(len(result.unmapped_champions)),
        "series_status": result.series_analysis.status,
        "series_game_status_counts": series_status_counts,
        "series_diagnostic_reason_counts": series_diagnostic_reasons,
        "game_transform_status": game_transform_status,
        "cutoff_status": "UNAVAILABLE",
        "transaction_status": "NOT_OPENED",
        "postgresql_changed": False,
    }
